bucket:
  strip: 1

packages:
  - name: collections
    actions:
      - name: create        
      - name: update        
      - name: delete        
      - name: getAll        
      - name: getSingle        
      - name: fork        
      - name: merge
        
  - name: project
    actions:
      - name: create        
        runtime: nodejs:10
      - name: deploy
        runtime: nodejs:10
      - name: deploy1
        runtime: nodejs:10
        limits:
          timeout: 10000
          memory: 768
