bucket:
  strip: 1

packages:
  - name: collections
    actions:
      - name: create
        environment: $(POSTMAN_API_KEY)
      - name: update
        environment: $(POSTMAN_API_KEY)
      - name: delete
        environment: $(POSTMAN_API_KEY)
      - name: getAll
        environment: $(POSTMAN_API_KEY)
      - name: getSingle
        environment: $(POSTMAN_API_KEY)
      - name: fork
        environment: $(POSTMAN_API_KEY)
      - name: merge
        environment: $(POSTMAN_API_KEY)
  - name: project
    actions:
      - name: create
        environment: $(POSTMAN_API_KEY)
        runtime: nodejs:10
